name: clockwork
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/buijs-dev/clockwork

environment:
  sdk: ^3.9.2

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
  pana: ^0.23.3