name: clockwork
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/buijs-dev/clockwork

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
